var GAME_LEVELS = [
["                                                                                ",
 "                                                                                ",
 "                                                                                ",
 "                                                                                ",
 "                                               l                  o             ",
 "                                             zzzzz                              ",
 "                                        xx    zzz                xxx            ",
 "                                              zzz           xx  xx!xx           ",
 "                                    o o      xxxxx              x!!!x           ",
 "                                                                xx!xx           ",
 "                                   xxxxx                         xvx            ",
 "                                                       xxx                      ",
 "                                             o                    o             ",
 "                       o                                s                       ",
 " x                    xxx                  xxxxx                         o      ",
 " x                 o                                 xxxxxxx                    ",
 " x @                                                 x     x                    ",
 " xxxxxxxxxxxx    xxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxx      xxxxxxxxxx",
 "            x    x            x   x                            x      x         ",
 "            x!!!!x            x!!!x                            x!!!!!!x         ",
 "            xxxxxx            x!!!x                            x!!!!!!x         ",
 "                              xxxxx                            xxxxxxxx         ",
 "                                                                                ",
 "                                                                                "],
["                                                                                ",
 "                                                                                ",
 "                       o                                                        ",
 "   @        o                  l                                                ",
 "xxxxxx              x     x zzzzzzz                        o            o       ",
 "     x              xx    x  zzzzz                          x                   ",
 "     x              x     xxxxxxxxx    xxxxxxx     xxxxxxxxxx   xxxxxx    xxx   ",
 "     x              x                  x     x!!!!!x        x!!!x    x    x     ",
 "     xxxxx     xxxxxx        s         x     xxxxxxx        x!!!x    x    x     ",
 "         x!!!!!x    xxxxxxxxxxxxxxxxxxxx                    xxxxx    x    x     ",
 "         xxxxxxx                                                     xx   x     ",
 "                                                                     x    x     ",
 "    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    x     ",
 "    x                                                                     x     ",
 "    x                                                                    xx     ",
 "    x                                                                     x     ",
 "    x                                                                     x     ",
 "    x o  o                                               o                x     ",
 "    xxxxxxxx                            xxxxxxxxx    xxxxxxxxxx     xxxxxxx     ",
 "    x              o    o       xxxxx                                     x     ",
 "    x           xxxxxxxxxxxx                                              x     ",
 "    x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x     ",
 "    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     "],

  ["                                                                                                                 ",
   "                                                                                                                 ",
   "                                                xxx                                                              ",
   "                                               x!!!x                                                             ",
   "                                               x!!!x                                                             ",
   "                                                x!x                                                              ",
   "                                                x!x                                                              ",
   "                                                xvx                                         xxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                                 ",
   "                                                                                                                 ",
   "                                                 o                                                   o           ",
   "                                              x    xx                             xxx       xxxxxxxxxxxxxxxxxxxxx",
   "                                              x     x                             x         x                    ",
   "                                              x     x                             x         x                    ",
   "                                              x     x                             x       xxx                    ",
   "                  o                           xx    x                        l    x         x                    ",
   "                                              x     x      o  o     x   x  zzzzz  x         x                    ",
   "               xxxxxxx      xx     xxx        x     x               x   x   zzz   x         x                    ",
   "              xx     xx      x     x          x     x     xxxxxx    x   x   xxxxxxxxx       x                    ",
   "             xx       xx     x     x          x    xx               x   x   x               x                    ",
   "     @       x         x     x     x          x     x               x   x   x               x                    ",
   "    xxx      x         x     x     x          x     x               x   xxxxx   xxx        xx                    ",
   "    x x      x         x     x     xx         x     x               x     o     x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!x     xx!!!!!!!!xxx    x!!!!!!!!!!!!!!!x           x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!x      xxxxxxxxxx      x!!!!!!!xx!!!!!!xxxxxxxxxxxxx xx  o o  xx                    ",
   "!!!!x x!!!!!!x         x!!!!!x                     xxx!!!!!!xxxxxxxxx              xx     xx                     ",
   "!!!!x x!!!!!!x         x!!!!!x  o        s        o xx!!!!!!xx                      xxxxxxx                      ",
   "!!!!x x!!!!!!x         x!!!!!xx                     x!!!!!!xxx                                                   ",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxxxxxxxxxxxxxxxx!!!xxx                                                      ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx                                                       "],
   ["                                                                                                                ",
    "  xxx  xxx   xxxxx   xxx  xxx                                                                                   ",
    "  x!xxxx!x  x!!!!!x  x!x  x!x                                                                                   ",
    "  x!!!!!!x  x!!x!!x  x!x  x!x                                                                                   ",
    "  xxx!!xxx  x!!x!!x  x!xxxx!x                                                                                   ",
    "    x!!x    x!!!!!x  x!!!!!!x                                                                                   ",
    "    xxxx     xxxxx    xxxxxx                                                                                    ",
    "                                                                                                                ",
    "  xxx xxx xxx  xxx  xxx   xxx                                                                                 ",
    "  x!x x!x x!x  x!x  x!!x  x!x                                                                                 ",
    "  x!x x!x x!x  x!x  x!!!x x!x                                                                                 ",
    "  x!xx!!!xx!x  x!x  x!xx!xx!x                                                                                 ",
    "   x!!!xx!!!x  x!x  x!x x!!!x                                                                                 ",
    "    xxx  xxx   xxx  xxx  xxxx                                                                                 ",
    "                                                                                                                ",
    "                                                                                                                ",
    "                                                                                                                "],

];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
